### ISSUE TITLE
Add to main highlight.js repo

### ISSUE THREAD

**Issue by Sjors** [pospi/highlightjs-solidity#1]
What needs to be done to get this included in https://github.com/isagalaev/highlight.js ?

**Comment by pospi** [comment]
Let's find out!
https://github.com/isagalaev/highlight.js/pull/1287

**Comment by marcoscaceres** [comment]
(I maintain hljs) I'm going to propose that the way you are distributing things at the moment is the right way to go (i.e., not to be included in core highlight.js). 

I'm moving to no longer accept languages into hljs core. It avoids a bunch of duplication, complexity, security problems - and places the original author in charge of maintaining their own language, which I think is best.

**Comment by marcoscaceres** [comment]
@pospi, if you'd like to move to move this over to the highlightjs org, you are free to do so via settings. You will retain full admin rights over the repository, etc.  

https://github.com/highlightjs

**Comment by pospi** [comment]
Sorry for being slack on this. Sounds like a good idea. I think I need to be added to the highlightjs org in order to do so, it's currently giving me a permission issue when I issue the ownership transfer.

**Comment by marcoscaceres** [comment]
Added you as a member... I think you should get an email invite... if not, just visit https://github.com/highlightjs and it should allow you to accept the invite there.

**Comment by pospi** [comment]
Hmm, nah. Still permission error. The easier thing to do may be to create the repo yourself, push it up via git and then add me as a collaborator just to that repo.

**Comment by marcoscaceres** [comment]
Agree. Let's do that :)

**Comment by marcoscaceres** [comment]
Ok, done! https://github.com/highlightjs/highlightjs-solidity - sent you an invite again and made you repo admin. 

Your work actually inspired us to do the separate repositories per language, so just an additional thanks just for that!

**Comment by pospi** [comment]
awesome! Happy to have helped (:
