### ISSUE TITLE
Error in-browser

### ISSUE THREAD

**Issue by mikeshultz** [pospi/highlightjs-solidity#2]
Received this when trying to use in browser: 

    solidity.js:16 Uncaught ReferenceError: module is not defined
        at solidity.js:16

**Comment by pospi** [comment]
That's pretty weird, what browser are you getting this in?

Are you still able to call `hljs.registerLanguage('solidity', hljsDefineSolidity);` and have it work? If so, you can probably ignore that error.

If not, this package is actually included with the main highlightjs library now, so you probably don't even need to use it directly. Just use the latest version of hljs and it should already be available!

**Comment by pospi** [comment]
Oh, my bad. Looks like the author hasn't merged it in yet after all- https://github.com/isagalaev/highlight.js/pull/1287

Let me know if registration doesn't work manually and I'll take a look. But I'm very surprised at this error- the "or" shorthand for managing undefined variables has never been a problem for me before :/

**Comment by pospi** [comment]
Note this is fixed in https://github.com/pospi/highlightjs-solidity/pull/5
